name = "MLJModels"
uuid = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.2.1"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
MLJBase = "0.2.0"

[extras]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NaiveBayes = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Clustering", "DecisionTree", "GLM", "GaussianProcesses", "MultivariateStats", "NaiveBayes", "Pkg", "ScikitLearn", "Test"]
