[deps]
BetaML = "024491cd-cc6b-443e-8034-08ea7eb7db2b"
CatBoost = "e2e10f9a-a85d-4fa9-b6b2-639a32100a12"
EvoLinear = "ab853011-1780-437f-b4b5-5de6f4777246"
EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
FeatureSelection = "33837fe5-dbff-4c9e-8c2f-c5612fe2b8b6"
Imbalance = "c709b415-507b-45b7-9a3d-1767c89fde68"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LaplaceRedux = "c52c1a26-f7c5-402b-80be-ba1e638ad478"
LightGBM = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a"
MLJBalancing = "45f359ea-796d-4f51-95a5-deb1a414c586"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJClusteringInterface = "d354fa79-ed1c-40d4-88ef-b8c7bd1568af"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJEnsembles = "50ed68f4-41fd-4504-931a-ed422449fee0"
MLJFlux = "094fc8d1-fd35-5302-93ea-dabda2abf845"
MLJGLMInterface = "caf8df21-4939-456d-ac9c-5fefbfb04c0c"
MLJIteration = "614be32b-d00c-4edb-bd02-1eb411ab5e55"
MLJLIBSVMInterface = "61c7150f-6c77-4bb1-949c-13197eac2a52"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
MLJMultivariateStatsInterface = "1b6a4a23-ba22-4f51-9698-8599985d3728"
MLJNaiveBayesInterface = "33e4bacb-b9e2-458e-9a13-5d9a90b235fa"
MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
MLJTSVDInterface = "7fa162e1-0e29-41ca-a6fa-c000ca4e7e7e"
MLJTestInterface = "72560011-54dd-4dc2-94f3-c5de45b75ecd"
MLJText = "5e27fcf9-6bac-46ba-8580-b5712f3d6387"
MLJTuning = "03970b2e-30c4-11ea-3135-d1576263f10f"
MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
Maxnet = "81f79f80-22f2-4e41-ab86-00c11cf0f26f"
NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36"
OneRule = "90484964-6d6a-4979-af09-8657dbed84ff"
OutlierDetectionNeighbors = "51249a0a-cb36-4849-8e04-30c7f8d311bb"
OutlierDetectionPython = "2449c660-d36c-460e-a68b-92ab3c865b3e"
ParallelKMeans = "42b8e9d4-006b-409a-8472-7f34b3fb58af"
PartitionedLS = "19f41c5e-8610-11e9-2f2a-0d67e7c5027f"
SIRUS = "cdeec39e-fb35-4959-aadb-a1dd5dede958"
SelfOrganizingMaps = "ba4b7379-301a-4be0-bee6-171e4e152787"
SymbolicRegression = "8254be44-1295-4e6a-a16d-46603ac705cb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
